baseURL = "https://monsterhunters.club"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "monsterhunters"
    description = ""
    favicon = ""
    message = "COMING SOON!"
    release = "Jan 1, 2026"
    background = ""
